import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function AddFields() {
  const router = useRouter();

  const handleAddFieldClick = () => {
    router.push('/addField'); // replace '/addField' with the actual path of the addField page
  };

  return (
    <>
      <Head>
        <title>Storeal App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className={styles.header}>
        <h1>STOREAL</h1>
        <p id="center">Distributed Database As A Service</p>
      </header>
      <button onClick={handleAddFieldClick}>Add Field</button>
    </>
  );
}
