import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
import { Button, Input, Table } from "reactstrap";
import React, { useEffect, useState } from "react";
import { useAccount, useContractWrite, usePrepareContractWrite, useWaitForTransaction } from "wagmi";
import axios from "axios";
import ContractABI from "../../artifacts/contracts/Storeal.sol/Storage.json";

export default function AddFields() {
  const router = useRouter();
  const { address } = useAccount()

  // useEffect(() => {response && contractCall(response)}, [response]);

  return (
    <>
      <Head>
        <title>Storeal App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className={styles.header}>
        <h1>STOREAL</h1>
        <p id="center">Distributed Database As A Service</p>
      </header>

      <Table> 
        <tr></tr>
      </Table>
      </>
  );
}
