import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { useAccount } from "wagmi";
//import { useRouter } from 'next/router';


const Home: NextPage = () => {
  //const router = useRouter();
  // const [isConnected, setIsConnected] = useState(false);
  const { address, isConnecting, isDisconnected } = useAccount();

  // const handleConnect = () => {
  //   setIsConnected(true);
  // };

  console.log(address, isConnecting, isDisconnected);

  useEffect(() => {
    if (!isDisconnected && address) window.location.href = "/addDocument";
  }, [isDisconnected, address]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Storeal App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <header className={styles.header}>
        <h1>STOREAL</h1>
        <p id="center">Distributed Database As A Service</p>
      </header>
      <body>
        <ConnectButton />
      </body>
      <footer className={styles.footer}>
        Made with ❤️ by your frens at Eth Denver 2023!
      </footer>
    </div>
  );
};

export default Home;
